name: Absolutely Fuzzy
favicon: null
layout_spectrum: 0.9157232900615782
typography_spectrum: 0.9037308245897293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.876805470790714
  lightness: 0.028195718536153436
  saturation: 0.23214536951854825
  rhythmicContrast: 0.7551404442638159
purpose: []
